services:
  - type: web
    name: askjonty
    env: python
    runtime: python-3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-render.txt
    startCommand: streamlit run app_lite.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama3-8b-8192
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2